name: disdrodb
channels:
  - conda-forge
  - defaults
dependencies:
  - click
  - dask
  - h5py
  - netCDF4
  - numpy
  - pandas
  - pyarrow
  - PyYAML
  - setuptools
  - xarray
  - sphinx
  - sphinx_rtd_theme

