name: disdrodb-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - click
  - h5py
  - netCDF4
  - pyarrow
  - PyYAML
  - setuptools
  - xarray
  - sphinx
  - sphinx_rtd_theme
  - jupyter
  - nbsphinx
  - dask
