rainfall_rate_32bit: ''
rainfall_accumulated_32bit: ''
weather_code_synop_4680: ''
weather_code_synop_4677: ''
weather_code_metar_4678: ''
weather_code_nws: ''
reflectivity_32bit: ''
mor_visibility: ''
sample_interval: ''
laser_amplitude: ''
number_particles: ''
sensor_temperature: ''
sensor_serial_number: ''
firmware_iop: ''
firmware_dsp: ''
sensor_heating_current: ''
sensor_battery_voltage: ''
sensor_status: ''
start_time: ''
sensor_time: ''
sensor_date: ''
station_name: ''
station_number: ''
rainfall_amount_absolute_32bit: ''
error_code: ''
sensor_temperature_pcb: ''
sensor_temperature_receiver: ''
sensor_temperature_trasmitter: ''
rainfall_rate_16_bit_30: ''
rainfall_rate_16_bit_1200: ''
rainfall_accumulated_16bit: ''
reflectivity_16bit: ''
rain_kinetic_energy: ''
snowfall_rate: ''
number_particles_all: ''
list_particles: ''
raw_drop_concentration: ''
raw_drop_average_velocity: ''
raw_drop_number: ''

