name: disdrodb
channels:
  - conda-forge
dependencies:
  - click
  - pyyaml
  - tqdm
  - pooch
  - requests
  - trollsift
  - h5py
  - netcdf4
  - pyarrow
  - pandas
  - dask[distributed]
  - xarray
  # Docs
  - jupyter
  - sphinx
  - sphinx-book-theme
  - nbsphinx
  # Testing
  - setuptools
  - pre_commit
  - pytest
  - pydantic
  - pip
