start_identifier: 'STX (start identifier)'
device_address: 'Device address (factory setting „00“) (NN)'
sensor_serial_number: 'Serial number (NNNN)'
firmware_dsp: 'Software-Version (N.NN)'
date_sensor: 'Date of the sensor (tt.mm.jj)'
time_sensor: 'Time of the sensor (on request) (hh:mm:ss)'
synop_4677_5min_weather_code: '5M SYNOP Tab.4677 (5 minutes mean value) (NN)'
synop_4680_5min_weather_code: '5M SYNOP Tab.4680 (5 minutes mean value) (NN)'
metar_4678_5min_weather_code: '5M METAR Tab.4678 (5 minutes mean value) (AAAAA)'
intensity_total_5min: '5M Intensity [mm/h] (5 minutes mean value) (NNN.NNN)'
synop_4677_weather_code: '1M SYNOP Tab.4677 (1 minute value) (NN)'
synop_4680_weather_code: '1M SYNOP Tab.4680 (1 minute value) (NN)'
metar_4678_weather_code: '1M METAR Tab.4678 (1 minute value) (AAAAA)'
intensity_total: '1M Intensity [mm/h] total precipitation (1 minute value) (NNN.NNN)'
intensity_liquid: '1M Intensity [mm/h] liquid precipitation (1 minute value) (NNN.NNN)'
intensity_solid: '1M Intensity [mm/h] solid precipitation (1 minute value) (NNN.NNN)'
accum_precip: 'Precipitation amount [mm] (Reset with command „RA“) (NNNN.NN)'
maximum_visibility: '1M Visibility in precipitation [0...99999m] (1 minute value) (NNNNN)'
radar_reflectivity: '1M Radar reflectivity [-9.9...99.9dBZ] (1 minute value) (NN.N)'
quality_measurement: '1M Measuring quality [0...100%] (1 minute value) (NNN)'
max_diameter_hail: '1M Maximum diameter hail [mm] (1 minute value) (N.N))'
laser_status: 'Status Laser (OK/on:0, off:1)'
static_signal: 'Static signal (OK:0, Error:1)'
laser_temperature_analog_status: 'Status Laser temperature (analogue) (OK:0, Error:1)'
laser_temperature_digital_status: 'Status Laser temperature (digital) (OK:0, Error:1)'
laser_current_analog_status: 'Status Laser current (analogue) (OK:0, Error:1)'
laser_current_digital_status: 'Status Laser current (digital) (OK:0, Error:1)'
sensor_status: 'Status Sensor supply (OK:0, Error:1)'
pane_heating_laser_head_current: 'Status Current pane heating laser head (OK:0, warning:1)'
pane_heating_receiver_head_current: 'Status Current pane heating receiver head (OK:0, warning:1)'
temperature_sensor_status: 'Status Temperature sensor (OK:0, warning:1)''
status_heating: 'Status Heating supply (OK:0, warning:1)'
heating_house_current_status: 'Status Current heating housing (OK:0, warning:1)'
heating_heads_current_status: 'Status Current heating heads (OK:0, warning:1)'
heating_carriers_current_status: 'Status Current heating carriers (OK:0, warning:1)'
control_output_laser_power_status: 'Status Control output laser power (OK:0, warning:1)'
reserve_status: 'Reserve Status (0)'
interior_temperature: 'Interior temperature [°C] (NNN)'
laser_temperature: 'Temperature of laser driver 0-80°C (NN)'
mean_laser_current: 'Mean value laser current [1/100 mA] (NNNN)'
control_voltage: 'Control voltage [mV] (reference value: 4010±5) (NNNN)'
optical_control_output: 'Optical control output [mV] (2300 … 6500) (NNNN)'
voltage_sensor_supply: 'Voltage sensor supply [1/10V] (NNN)'
ambient_temperature: 'Ambient temperature [°C] (NNN.N)'
voltage_heating_supply: 'Voltage Heating supply [1/10 V] (only 5.4110.x1.xxx, otherwise “999”) (NNN)'
heating_house_current: 'Current heating housing [mA] (only 5.4110.x1.xxx, otherwise “9999”) (NNNN)'
heating_heads_current: 'Current heating heads [mA] (only 5.4110.x1.xxx, otherwise “9999”) (NNNN)'
heating_carriers_current: 'Current heating carriers [mA] (only 5.4110.x1.xxx, otherwise “9999”) (NNNN)'
number_particles: 'Number of all measured particles (NNNNN)'
number_particles_internal_data: ''
number_particles_min_speed: ''
number_particles_min_speed_internal_data: ''
number_particles_max_speed: ''
number_particles_max_speed_internal_data: ''
number_particles_min_diameter: ''
number_particles_min_diameter_internal_data: ''
number_particles_no_hydrometeor: ''
number_particles_no_hydrometeor_internal_data: ''
number_particles_no_classification: ''
number_particles_no_classification_internal_data: ''
number_particles_class_1: ''
number_particles_class_1_internal_data: ''
number_particles_class_2: ''
number_particles_class_2_internal_data: ''
number_particles_class_3: ''
number_particles_class_3_internal_data: ''
number_particles_class_4: ''
number_particles_class_4_internal_data: ''
number_particles_class_5: ''
number_particles_class_5_internal_data: ''
number_particles_class_6: ''
number_particles_class_6_internal_data: ''
number_particles_class_7: ''
number_particles_class_7_internal_data: ''
number_particles_class_8: ''
number_particles_class_8_internal_data: ''
number_particles_class_9: ''
number_particles_class_9_internal_data: ''
precipitation_spectrum: ''
diameter_speed: ''
